# -*- coding: utf-8 -*-
"""196Final.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CJwkozHpBGKvRA8bPxyl7rsxT-AFUFKd
"""

# Commented out IPython magic to ensure Python compatibility.
# %html 
<script type='text/javascript' src='https://10ay.online.tableau.com/javascripts/api/viz_v1.js'></script><div class='tableauPlaceholder' style='width: 1700px; height: 827px;'><object class='tableauViz' width='1700' height='827' style='display:none;'><param name='host_url' value='https%3A%2F%2F10ay.online.tableau.com%2F' /> <param name='embed_code_version' value='3' /> <param name='site_root' value='&#47;t&#47;196final' /><param name='name' value='Book1smokebygender&#47;Dashboard1' /><param name='tabs' value='no' /><param name='toolbar' value='yes' /><param name='showAppBanner' value='false' /></object></div>

# Import Tableau Visualization 
from IPython.display import IFrame
IFrame('https://public.tableau.com/views/Smoking_new/Dashboard3?:embed=y&:display_count=yes&:showVizHome=no', 
       width=900, height=800)

# Commented out IPython magic to ensure Python compatibility.
# %%html
# <script type='text/javascript' src='https://10ay.online.tableau.com/javascripts/api/viz_v1.js'></script><div class='tableauPlaceholder' style='width: 1500px; height: 827px;'><object class='tableauViz' width='1500' height='827' style='display:none;'><param name='host_url' value='https%3A%2F%2F10ay.online.tableau.com%2F' /> <param name='embed_code_version' value='3' /> <param name='site_root' value='&#47;t&#47;196final' /><param name='name' value='Smoking_graph&#47;Dashboard4' /><param name='tabs' value='no' /><param name='toolbar' value='yes' /><param name='showAppBanner' value='false' /></object></div>

